[package]

name = "solidoak"
version = "0.1.1"
authors = ["oakes <zsoakes@gmail.com>"]
build = "build.rs"

[dependencies.gdk]

git = "https://github.com/rust-gnome/gdk"

[dependencies.glib]

git = "https://github.com/rust-gnome/glib"

[dependencies.gtk]

git = "https://github.com/oakes/gtk"
features = ["gtk_3_10"]

[dependencies.neovim-rs]

git = "https://github.com/oakes/neovim-rs"

[dependencies.rustc-serialize]

rustc-serialize = "0.3"
